"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var SalaryRecord_1 = require("./SalaryRecord");
var SalaryManager_1 = require("./SalaryManager");
var salary1 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.JAN, 5000000);
var salary2 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.FEB, 6000000);
var salary3 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.MAR, 7000000);
var salary4 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.APR, 8000000);
var salary5 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.MAR, 9000000);
var salary6 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.JUN, 10000000);
var salary7 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.JUL, 11000000);
var salary8 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.AUG, 12000000);
var salary9 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.SEP, 13000000);
var salary10 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.OCT, 14000000);
var salary11 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.NOV, 15000000);
var salary12 = new SalaryRecord_1.SalaryRecord(SalaryRecord_1.Month.DEP, 16000000);
var salaryManager = new SalaryManager_1.SalaryManager();
salaryManager.insertLast(salary1);
salaryManager.insertLast(salary2);
salaryManager.insertLast(salary3);
salaryManager.insertLast(salary4);
salaryManager.insertLast(salary5);
salaryManager.insertLast(salary6);
salaryManager.insertLast(salary7);
salaryManager.insertLast(salary8);
salaryManager.insertLast(salary9);
salaryManager.insertLast(salary10);
salaryManager.insertLast(salary11);
salaryManager.insertLast(salary12);
console.log(salaryManager);
salaryManager.showList();
salaryManager.showSumOfSalary();
salaryManager.findMaxSalary();
